@startuml
scale 550 width

state Philosofer {
  [*] --> Thinking
  Thinking --> Thinking : Grabs 1st fork
  Thinking ----> Eating : Grabs 2nd fork
  Eating -----> Thinking : Drops a fork
  Thinking --> Thinking : Drops other fork
}

@enduml
